const PEERJS_URL="https://cdn.jsdelivr.net/npm/peerjs@1.5.5/dist/peerjs.min.js";
const DEMO_BASE="https://z999q.github.io/webterm/packages/ppshir/demo/";
let peer=null,connection=null,sessionId=null,peerId=null,peerLoadPromise=null,reconnectTimer=null;
const DEMOS={instagram:"Instagram-style Demo",facebook:"Facebook-style Demo",google:"Google-style Demo",microsoft:"Microsoft-style Demo"};
function randomSession(){return Math.random().toString(36).substring(2,8).toUpperCase()}
function cleanup(){if(reconnectTimer){clearTimeout(reconnectTimer);reconnectTimer=null}if(connection){try{connection.close()}catch{}connection=null}if(peer){try{peer.destroy()}catch{}peer=null}sessionId=null;peerId=null}
function loadPeerJS(){if(window.Peer)return Promise.resolve(window.Peer);if(peerLoadPromise)return peerLoadPromise;peerLoadPromise=new Promise((resolve,reject)=>{const existing=document.querySelector('script[data-webterm-peerjs="1"]');if(existing){let n=0;const timer=setInterval(()=>{if(window.Peer){clearInterval(timer);resolve(window.Peer)}else if(++n>300){clearInterval(timer);reject(new Error("PeerJS script did not initialize"))}},50);return}const script=document.createElement("script");script.src=PEERJS_URL;script.async=true;script.dataset.webtermPeerjs="1";script.onload=()=>window.Peer?resolve(window.Peer):reject(new Error("PeerJS loaded but window.Peer is unavailable"));script.onerror=()=>reject(new Error("Unable to load PeerJS browser bundle"));document.head.appendChild(script)});return peerLoadPromise.catch(e=>{peerLoadPromise=null;throw e})}
function help(t){t.print("");t.print("PPSHIR - WebRTC Security Awareness Lab");t.print("");t.print("Commands:");t.print("  ppshir                 Start the demo hub");t.print("  ppshir list            List demo pages");t.print("  ppshir instagram       Start + open Instagram-style demo");t.print("  ppshir facebook        Start + open Facebook-style demo");t.print("  ppshir google          Start + open Google-style demo");t.print("  ppshir microsoft       Start + open Microsoft-style demo");t.print("  ppshir status          Show session status");t.print("  ppshir stop            Stop the session");t.print("  ppshir help            Show help");t.print("");t.print("Synthetic training data only. Real passwords, OTPs and secrets are never requested or transmitted.");t.print("")}
function list(t){t.print("");t.print("Available PPSHIR training scenarios:");Object.entries(DEMOS).forEach(([k,v])=>t.print(`  ${k.padEnd(10)} ${v}`));t.print("")}
function handleData(t,d){if(!d||typeof d!=="object")return;if(d.type==="hello"){t.print(`Demo connected: ${d.platform||"unknown"}`);return}if(d.type==="training-event"){t.print("");t.print("=== SECURITY TRAINING EVENT ===");t.print(`Platform: ${String(d.platform||"unknown")}`);t.print(`Action: ${String(d.action||"unknown")}`);t.print(`Demo name: ${String(d.demoName||"")}`);t.print(`Training code supplied: ${d.trainingCodeSupplied?"YES":"NO"}`);t.print("Real password transmitted: NO");t.print("Transport: WebRTC DataChannel");t.print(`Session: ${sessionId}`);t.print("================================");t.print("")}}
function attach(conn,t){if(connection&&connection!==conn){try{conn.close()}catch{}return}connection=conn;t.print("");t.print(`Demo connection received: ${conn.peer}`);conn.on("open",()=>{t.print("WebRTC DataChannel: OPEN");try{conn.send({type:"hello",session:sessionId})}catch{}});conn.on("data",d=>handleData(t,d));conn.on("close",()=>{if(connection===conn)connection=null;t.print("WebRTC DataChannel: CLOSED")});conn.on("error",e=>t.print(`WebRTC DataChannel error: ${e.message||e}`))}
function reconnect(t){if(reconnectTimer||!peer||peer.destroyed)return;reconnectTimer=setTimeout(()=>{reconnectTimer=null;if(peer&&!peer.destroyed&&peer.disconnected){t.print("Attempting PeerServer reconnection...");try{peer.reconnect()}catch(e){t.print(`Reconnect error: ${e.message||e}`);reconnect(t)}}},2500)}
function openDemo(t,name){if(!peerId||!sessionId){t.print("ppshir: session is not ready yet.");return}const url=`${DEMO_BASE}${name}/?peer=${encodeURIComponent(peerId)}&session=${encodeURIComponent(sessionId)}`;t.print("");t.print(`${DEMOS[name]}:`);t.print(url);t.print("");try{const w=window.open(url,"_blank","noopener,noreferrer");if(!w)t.print("Browser blocked the new tab. Open the URL above manually.")}catch{t.print("Open the URL above manually.")}}
async function start(t,selected){if(peer){if(selected)openDemo(t,selected);else t.print("ppshir: session already running.");return}sessionId=randomSession();t.print("");t.print("PPSHIR Security Awareness Lab");t.print("--------------------------------");t.print(`Session ID: ${sessionId}`);t.print("Loading PeerJS browser bundle...");try{const PeerClass=await loadPeerJS();t.print("PeerJS browser bundle loaded.");t.print("Creating WebRTC peer...");peer=new PeerClass({debug:0});peer.on("open",id=>{peerId=id;t.print("");t.print("Session ready.");t.print(`Peer ID: ${id}`);t.print("");if(selected)openDemo(t,selected);else{t.print("Demo hub:");t.print(`${DEMO_BASE}?peer=${encodeURIComponent(id)}&session=${encodeURIComponent(sessionId)}`);t.print("");t.print("Waiting for participant...")}});peer.on("connection",c=>attach(c,t));peer.on("error",e=>{t.print(`PPSHIR error: ${e.type||"unknown"} ${e.message||""}`);if(e.type==="network")reconnect(t)});peer.on("disconnected",()=>{t.print("PPSHIR signaling connection disconnected.");reconnect(t)});peer.on("close",()=>t.print("PPSHIR peer closed."))}catch(e){t.print(`ppshir: ${e.message||e}`);cleanup()}}
export default{description:"Multi-demo WebRTC security-awareness laboratory",async execute(args,t){const cmd=(args[0]||"start").toLowerCase();if(["help","-h","--help"].includes(cmd))return help(t);if(cmd==="list")return list(t);if(cmd==="status"){if(!peer)return t.print("PPSHIR: no active session.");t.print(`Session ID: ${sessionId}`);t.print(`Peer ID: ${peerId||"connecting..."}`);t.print(`Signaling: ${peer.disconnected?"DISCONNECTED":"CONNECTED"}`);t.print(`DataChannel: ${connection&&connection.open?"OPEN":"waiting"}`);return}if(cmd==="stop"){if(!peer)return t.print("PPSHIR: no active session.");cleanup();return t.print("PPSHIR session stopped.")}if(Object.prototype.hasOwnProperty.call(DEMOS,cmd))return start(t,cmd);if(cmd==="start")return start(t,null);t.print(`ppshir: unknown command '${cmd}'`);t.print("Run 'ppshir help' for usage.")}};
